### ISSUE TITLE
Modelado

### ISSUE THREAD

**Issue by AugustoCarrasco** [4GeeksAcademy/pt-48-lend-me-something-lovera-gonzalez-meisus-carrasco#6]
### Modelado pendiente

- [ ] Diccionarios
- [x] Valores -- Augusto
- [x] Indices -- Adrian
- [x] Mercados -- Anderson
- [x] Usuario -- Juan
- [ ] Extension de usuario con profile data -- Juan
- [ ] Extension de usuario con settings -- Augusto
- [ ] Favoritos

**Comment by juanmeisus** [comment]
modelo usuario:
campos:
- [x] email, unique, nullable= false, string
- [x] password , nullable=false, string (20)
- [x] create at , date, nullable=false, string 
- [x] id , Pk
- [x] repr
- [x] serialize

**Comment by juanmeisus** [comment]
añadido User repository completed

**Comment by AndyGH86** [comment]
Modelo Market:

- [x] id primary key (integer)
- [x] name (string(50) nullable = false)
- [x] region (string(50) nullable false  )
- [x] headquarters (string(200) nullable false)
- [x] currency (string (50) nullable false)
- [x] opentime (string(50) nullable false)
- [x] closetime (string(50) nullable false)
- [x] __repr__ 
- [x] def serialize

**Comment by AugustoCarrasco** [comment]
Extensión de usuario con profile data -- Juan
- [ ] first_name
- [ ] last_name
- [ ] address
- [ ] ID type
- [ ] ID
- [ ] DOB
